### ISSUE TITLE
Commit Message Standards

### ISSUE THREAD

**Issue by umutucak** [Luxembourg-Open-Source-Club/BICS-BOT#1]

**Comment by PedroS235** [comment]
Here is a standard I came across:

- Commits should be well-scoped and frequent. This should reflect on the commit messages, which are expected to be short (with a maximum of 72 characters) and clear, indicating exactly what the commit does. 

- Commit messages should start with `[type of commit]` followed by a message. Here is a list of the commit types:
    * **[feat]** - a new feature was introduced
    * **[fix]** - a bug was fixed
    * **[chore]** - changes that do not modify the source code, but things like dependencies
    * **[refactor]** - changes that does not fix a bug nor implements a new feature
    * **[docs]** - updates on the documentation
    * **[style]** - Changes that occur when formatting is applied
    * **[test]** - Addition of new tests
    * **[perf]** - Performance improvements were made
    * **[build]** - changes that affect the build system, such as cmakelists
    * **[revert]** - reverts to a previous commit
- Some examples:
    * [fix] - bug fix when launching the s_graphs launch file
    * [docs] - added a new introduction section
    * [feat] - support to control tello with a keyboard.

**Comment by umutucak** [comment]
Solved with [this](https://github.com/Luxembourg-Open-Source-Club/.github/blob/main/CONVENTIONS.md#commits-conventions)
