### ISSUE TITLE
Birthday feature

### ISSUE THREAD

**Issue by PedroS235** [Luxembourg-Open-Source-Club/BICS-BOT#10]
Modify the intro command so that it also give the chance to add the birthday. In case a student gives it, the bot would send a message in the general chat to mention that its a student(s) birthday.

There would be an event driven that would run every day and check the registered birthdays

**Comment by ivomeister** [comment]
Same!!!!!

**Comment by umutucak** [comment]
# Expected behaviour
Students are given the option to enter a **birthday** when they use `/intro`.

There should be an event-based script that sends a message automatically on the server for that student's birthday.
