### ISSUE TITLE
Remove main file argument -c

### ISSUE THREAD

**Issue by umutucak** [Luxembourg-Open-Source-Club/BICS-BOT#15]
Remove the TOKEN_BOT_CLONE, and remove the -c flag function

**Comment by PedroS235** [comment]
### Extra Info
main.py accepts an argument `-c` which is a flag that changes which token to pick from .env file. This is no longer required, and it is thus deprecated.

**Comment by PedroS235** [comment]
Hello @AfaqShuaib09, thank you for your interest. It's all yours!
