### ISSUE TITLE
Implementation of a new BSP help command

### ISSUE THREAD

**Issue by PedroS235** [Luxembourg-Open-Source-Club/BICS-BOT#28]
**Is your feature request related to a problem? Please describe.**
This feature is related to issue (#27), where the idea would be to create a new command, such as `/bsp` which would contain all the necessary information and links which would be useful for the BSP.

**Describe the solution you'd like**
Create a new cog command, similar to the `/useful_links`, but for BSP purposes.

**Comment by ra-kiss** [comment]
Could you assign this issue to me please?
