### ISSUE TITLE
Branch Standards

### ISSUE THREAD

**Issue by PedroS235** [Luxembourg-Open-Source-Club/BICS-BOT#3]
Branch should also have standards, such as always have at least 2 active branches. An example would be `main` and `dev`, where `main` is a stable branch and `dev` a development branch. 

- New branches should always be created from `dev`, never from `main`, and should be named in lower case, with hyphens as separators. Ideally, branches should be very well-scoped, with this reflecting on their naming. I suggest utilizing the following prefixes

    - `feature/...`: for indicating new features;
    - `bugfix/...`: for indicating bug fixes
    - `refactor/...`: for indicating code refactoring;;

- Once a branch has fulfilled its purpose, a new pull request should be created, and assigned to another team member who will be responsible for reviewing the code and merging it into the `dev` branch.

**Comment by umutucak** [comment]
Solved with [this](https://github.com/Luxembourg-Open-Source-Club/.github/blob/main/CONVENTIONS.md#branch-conventions)
