### ISSUE TITLE
Add missing functions docstrings

### ISSUE THREAD

**Issue by PedroS235** [Luxembourg-Open-Source-Club/BICS-BOT#43]
# Is your feature request related to a problem? Please describe.
Yes. The code source contains a lot of functions/methods that do not contain any docstrings, explaining what they do, what they accept/output.

# Describe the solution you'd like
Add docstrings to all functions that do not contain one.

**Comment by JAENAI** [comment]
Can you assign this to me?

**Comment by PedroS235** [comment]
@JAENAI I have assigned you to both issues you requested, but try to focus on one, please. Anyway, thanks for contributing :smiley:!
