### ISSUE TITLE
Migrate virtual environment to Conda

### ISSUE THREAD

**Issue by StEvUgnIn** [Luxembourg-Open-Source-Club/BICS-BOT#45]
# Is your feature request related to a problem? Please describe.
- Python developed a solution named `virtualenv` to solve the impedance problem for software installations.
- This problem keeps troubling developing since Python 3 became stable.
- Many developers use docker to create virtual environments to avoid these problems.
- Anaconda became the new solution to create *workable* virtual environments

Please read this:
- https://dev.to/chrisparaiso/fighting-with-venv-in-python-2p60
- https://dev.to/bowmanjd/python-tools-for-managing-virtual-environments-3bko

I don't think we should use venv in 2023, especially with Python 4 soon to be released.

# Describe the solution you'd like
- Provide the user an environment file for anaconda.
- Provide the python version to use to all contributors of the repository.

# Describe alternatives you've considered
- Provide the python version to use with requirements.txt and venv
- Write a Dockerfile

# Additional context
Venv environments are local and not exportable to other installations on a different session / computer.

**Comment by PedroS235** [comment]
Thanks for the issue, and indeed, that is one of the problems, aa we need to execute where the main.py is located.

**Comment by StEvUgnIn** [comment]
Have you read the links that I shared? Virtual env comes with many issues when working in team.

**Comment by PedroS235** [comment]
Well, I don't see the issues. One is about not liking to type source `.venv/bing/activate` which is stupid. You can simply create an alias for this if you really don't want to type the whole thing. The other is a comparison about all the available alternatives. 

Now, you can very well create the Conda config, which you already did. I don't mind on that. @umutucak what about you? So that case you have the possibilities to use whatever you want. I personally won't use Conda, find it too much. Poetry, I already see myself using. It's a kinda of alternative to rust cargo.

**Comment by umutucak** [comment]
`venv`s are what we have now, and changing it won't really yield much result. Anyone can use anything they want, no one even needs to use virtual environments, you can just install everything on your local installation of you want. I don't see a benefit to this.

`venv` is easy and simple, and it was what we taught to the others already. No need to confuse people. If adding these configuration files does not take away from the `venv` solution, then they can be implemented. But like I said on Discord about other things, I would much rather have focus on "real" issues :+1:

**Comment by umutucak** [comment]
@StEvUgnIn This issue for now will not be fixed as it introduces a second file to maintain for dependencies. We do not want to increase maintenance surface for no gain as no one uses conda.
